// This file is auto-generated by scripts/generate-registry.js
// Do not edit this file manually.

const cmd_basic_help_0 = require("../features/basic/commands/help.js");
const cmd_basic_info_1 = require("../features/basic/commands/info.js");
const cmd_basic_ping_2 = require("../features/basic/commands/ping.js");
const cmd_basic_whoami_3 = require("../features/basic/commands/whoami.js");
const cmd_games_answer_4 = require("../features/games/commands/answer.js");
const cmd_games_dice_5 = require("../features/games/commands/dice.js");
const cmd_games_word_quiz_6 = require("../features/games/commands/word-quiz.js");
const cmd_tools_fortune_7 = require("../features/tools/commands/fortune.js");
const cmd_tools_weather_weekly_8 = require("../features/tools/commands/weather-weekly.js");
const cmd_tools_weather_9 = require("../features/tools/commands/weather.js");

// 아직 Features가 JS이므로 require를 유지하고, any 배열로 내보냅니다.
export const commands: any[] = [
  cmd_basic_help_0,
  cmd_basic_info_1,
  cmd_basic_ping_2,
  cmd_basic_whoami_3,
  cmd_games_answer_4,
  cmd_games_dice_5,
  cmd_games_word_quiz_6,
  cmd_tools_fortune_7,
  cmd_tools_weather_weekly_8,
  cmd_tools_weather_9,
];
