// This file is auto-generated by scripts/generate-registry.js
// Do not edit this file manually.

const cmd_admin_admin_data_0 = require('../features/admin/commands/admin-data.js');
const cmd_admin_admin_log_1 = require('../features/admin/commands/admin-log.js');
const cmd_admin_admin_notice_2 = require('../features/admin/commands/admin-notice.js');
const cmd_basic_help_3 = require('../features/basic/commands/help.js');
const cmd_basic_info_4 = require('../features/basic/commands/info.js');
const cmd_basic_ping_5 = require('../features/basic/commands/ping.js');
const cmd_basic_whoami_6 = require('../features/basic/commands/whoami.js');
const cmd_games_answer_7 = require('../features/games/commands/answer.js');
const cmd_games_dice_8 = require('../features/games/commands/dice.js');
const cmd_games_word_quiz_9 = require('../features/games/commands/word-quiz.js');
const cmd_tools_fortune_10 = require('../features/tools/commands/fortune.js');
const cmd_tools_weather_weekly_11 = require('../features/tools/commands/weather-weekly.js');
const cmd_tools_weather_12 = require('../features/tools/commands/weather.js');

module.exports = {
  commands: [
    cmd_admin_admin_data_0,
    cmd_admin_admin_log_1,
    cmd_admin_admin_notice_2,
    cmd_basic_help_3,
    cmd_basic_info_4,
    cmd_basic_ping_5,
    cmd_basic_whoami_6,
    cmd_games_answer_7,
    cmd_games_dice_8,
    cmd_games_word_quiz_9,
    cmd_tools_fortune_10,
    cmd_tools_weather_weekly_11,
    cmd_tools_weather_12
  ]
};
